# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lolita-editable-list}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["IT House (Latvia)"]
  s.date = %q{2011-04-01}
  s.description = %q{With this gem you are able to change content right on the list table, changes will be saved through ajax call.}
  s.email = %q{gatis@ithouse.lv}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/views/components/lolita/list/editable/_body_cell.html.erb",
    "app/views/components/lolita/list/editable/_display.html.erb",
    "app/views/components/lolita/list/editable/_row.html.erb",
    "lib/generators/lolita_editable_list/assets_generator.rb",
    "lib/generators/lolita_editable_list/install_generator.rb",
    "lib/lolita-editable-list.rb",
    "lib/lolita-editable-list/configuration/editable_list.rb",
    "lib/lolita-editable-list/configuration/list.rb",
    "lib/lolita-editable-list/version.rb",
    "lolita-editable-list.gemspec",
    "public/stylesheets/lolita/editable.css",
    "spec/configuration/editable_list_spec.rb",
    "spec/factories/post.rb",
    "spec/spec_helper.rb",
    "spec/test_orm/active_record.rb",
    "spec/test_orm/active_record/post.rb",
    "spec/test_orm/config/active_record.yml",
    "spec/test_orm/db/migrate/01_create_posts.rb",
    "spec/test_orm/rails/config/application.rb",
    "spec/test_orm/rails/config/enviroment.rb",
    "spec/test_orm/rails/config/routes.rb",
    "spec/test_orm/rails/log/development.log",
    "spec/test_orm/support.rb"
  ]
  s.homepage = %q{http://github.com/ithouse/lolita-list-edit}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{List inline editing for Lolita}
  s.test_files = [
    "spec/configuration/editable_list_spec.rb",
    "spec/factories/post.rb",
    "spec/spec_helper.rb",
    "spec/test_orm/active_record.rb",
    "spec/test_orm/active_record/post.rb",
    "spec/test_orm/db/migrate/01_create_posts.rb",
    "spec/test_orm/rails/config/application.rb",
    "spec/test_orm/rails/config/enviroment.rb",
    "spec/test_orm/rails/config/routes.rb",
    "spec/test_orm/support.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<lolita>, ["~> 3.0.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<lolita>, ["~> 3.0.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
    else
      s.add_dependency(%q<lolita>, ["~> 3.0.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<lolita>, ["~> 3.0.7"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    end
  else
    s.add_dependency(%q<lolita>, ["~> 3.0.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<lolita>, ["~> 3.0.7"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
  end
end

